global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.172:9100']
  - job_name: 'spring_app'
    static_configs:
      - targets: ['192.168.0.172:8080']

    metrics_path: '/actuator/prometheus'
    scheme: http

