global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['HOST IP:9100']
  - job_name: 'spring_app'
    static_configs:
      - targets: ['HOST IP:8080']

    metrics_path: '/actuator/prometheus'
    scheme: http

